apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-admission
  namespace: kube-system
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  template:
    metadata:
      labels:
        name: ingress-admission
      annotations:
        build: "https://gitlab.digital.homeoffice.gov.uk/go/kube-ingress-control"
        owner: "devops@digital.homeoffice.gov.uk"
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: 'kubernetes.io/role'
                operator: In
                values: [ master ]
      serviceAccount: admission-ingress
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.1
        resources:
          limits:
            cpu: 100m
            memory: 60Mi
        env:
        - name: DOMAIN
          value: ingress-admission.${KUBE_NAMESPACE}.svc.cluster.local
        - name: TLS_CA
          value: /caroot/caroot.pem
        volumeMounts:
        - name: caroot
          mountPath: /caroot
          readOnly: true
      - name: ingress-admission
        image: quay.io/ukhomeofficedigital/ingress-admission:v0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
        env:
        - name: TLS_CERT
          value: /certs/tls.pem
        - name: TLS_KEY
          value: /certs/tls-key.pem
        ports:
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /health
            port: https
            scheme: HTTPS
        livenessProbe:
          httpGet:
            path: /health
            port: https
            scheme: HTTPS
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
      volumes:
      - name: caroot
        configMap:
          name: caroot
