---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: acp:ingress-admission
rules:
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["externaladmissionhookconfigurations"]
  verbs: ["create", "update", "delete"]
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- nonResourceURLs: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: acp:ingress-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acp:ingress-admission
subjects:
- kind: ServiceAccount
  name: ingress-admission
  namespace: kube-admission
