apiVersion: admissionregistration.k8s.io/v1lapha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: acp.io.homeoffice.gov.uk.ingress-admission
spec:
  externalAdmissionHooks:
  - name: ingress-admission
    rules:
    - operations:
      - CREATE
      - UPDATE
      apiGroups:
      - ""
      apiVersions:
      - v1
      resources:
      - ingress
    failurePolicy: Ignore
    clientConfig:
      service:
        namespace: kube-system
        name: ingress-control
      caBundle:
