apiVersion: v1
kind: Service
metadata:
  labels:
    name: ingress-admission
  name: ingress-admission
spec:
  clusterIP: 10.10.22.100
  selector:
    name: ingress-admission
  ports:
  - name: https
    port: 443
    targetPort: 8443
